import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Header from "./components/header";
import Footer from "./components/footer";

const EurostileEx = localFont({
  src: "./fonts/EurostileLTStd-Ex2.otf",
  variable: "--font-eurostile-Ex",
  weight: "100 900",
});
const Eurostile = localFont({
  src: "./fonts/EurostileLTStd.otf",
  variable: "--font-eurostile",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${EurostileEx.variable} ${Eurostile.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
